### ISSUE TITLE
online plotting website

### ISSUE THREAD

**Issue by wyq-cloud** [IDEA-FinAI/ChartBench#3]
Hi, Thank you for your great work. We want to generate data by ourselves, may I ask what is the online plotting website mentioned in section 3.1 for drawing charts? Thank you!

**Comment by XuZhengzhuo** [comment]
We use [Matplotlib](https://matplotlib.org/), [pyEchart](https://pyecharts.org/#/) and [genescloud](https://www.genescloud.cn/chart/ChartOverview). I hope it will be helpful for you.
